include:
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Fpublish-image.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Fdeploy-eks.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Fbuild-app-maven-jdk17.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Fupdate-manifest.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Fnotification.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'
  - remote: 'https://gitlab.com/api/v4/projects/28640386/repository/files/.gitlab%2Fci%2Frelease.gitlab-ci.yml/raw?ref=main&private_token=gyxKKMLyoZ9yWrxqWGJg&ext=.yml'

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_COMMIT_MESSAGE !~ /^chore/'
    - if: '$CI_COMMIT_BRANCH == "qa" && $CI_COMMIT_MESSAGE !~ /^chore/'
    - if: '$CI_COMMIT_BRANCH == "staging" && $CI_COMMIT_MESSAGE !~ /^chore/'
    - if: '$CI_COMMIT_BRANCH == "develop" && $CI_COMMIT_MESSAGE !~ /^chore/'
      when: always
    - when: never

variables:
  DEPLOYMENT_NAME: subscription-service
  ENABLE_OVERRIDE_NS: "false"
  FILE_OUTPUT: namespace/daw-low-services/4.deployment/subscription-service/2.subscription-service.yaml
  NAMESPACE: daw-low-services
  OPERATION_REPO: git@gitlab.com:hcglab/dayaway/dayaway-operations.git
  STAGE_BUILD: DEV

stages:
  - install
  - build_app
  - publish_image
  - update_manifest
  - deploy
  - notification
